// File automagically generated by the "embed" tool
// To install the tool:
// go install https://githib.com/flevin58/embed@latest
//

package images

import _ "embed"


//go:embed runner.png
var Runner_png []byte

